# Generated by Django 5.1.4 on 2024-12-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='spend',
            field=models.FloatField(db_default=0),
        ),
    ]
